### PR TITLE
modals and lists

### PR DESCRIPTION
**Pull request by praveenreddy1798**
Modals and lists

modals-and-lists

### CODE REVIEW

**Review by TejasShekar — APPROVED** [review]
Looks good to merge

**Comment by whosmudassir** [comment]
Super cool 🔥 - i guess the "|" in the navbar at right most end is the only thing to be checked.

**Review by whosmudassir — COMMENTED** [review]
Super cool 🔥 - i guess the "|" in the navbar at right most end is the only thing to be checked.

**Review by whosmudassir — APPROVED** [review]

**Review by vaibhav18matere — COMMENTED** [review]
looks good

**Pull request merged**
